FROM python:3.7-slim

# System dependencies
RUN apt-get update && \
apt-get install git python3-pip default-libmysqlclient-dev sudo default-jre default-jdk -y 

VOLUME /Sites/online_test

ADD requirements/requirements-* /tmp/

RUN pip install --upgrade pip setuptools wheel

RUN pip install -r /tmp/requirements-codeserver.txt

# Create directories
RUN mkdir -p /Sites/online_test/yaksh_data/output \
             /Sites/online_test/yaksh_data/data

WORKDIR /Sites/online_test

ADD docker/Files/Start-codeserver.sh /Sites/Start-codeserver.sh
RUN chmod +x /Sites/Start-codeserver.sh

EXPOSE 53579

CMD ["/Sites/Start-codeserver.sh"]
