# Generated by Django 3.1.7 on 2025-12-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0031_auto_20251210_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('bash', 'Bash'), ('c', 'C Language'), ('cpp', 'C++ Language'), ('java', 'Java Language'), ('scilab', 'Scilab'), ('micropython', 'MicroPython'), ('r', 'R'), ('other', 'Other')], max_length=24),
        ),
    ]
