# Generated by Django 3.1.7 on 2025-12-17 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0032_auto_20251216_1850'),
        ('yaksh', '0032_auto_20251217_1919'),
    ]

    operations = [
    ]
